# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/zte/p839v55/setup-makefiles.sh

# ADSP
PRODUCT_COPY_FILES += \
    vendor/zte/p839v55/proprietary/bin/adsprpcd:system/bin/adsprpcd \
    vendor/zte/p839v55/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so

# Audio
PRODUCT_COPY_FILES += \
    vendor/zte/p839v55/proprietary/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:system/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    vendor/zte/p839v55/proprietary/etc/acdbdata/MTP/MTP_General_cal.acdb:system/etc/acdbdata/MTP/MTP_General_cal.acdb \
    vendor/zte/p839v55/proprietary/etc/acdbdata/MTP/MTP_Global_cal.acdb:system/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    vendor/zte/p839v55/proprietary/etc/acdbdata/MTP/MTP_Handset_cal.acdb:system/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/zte/p839v55/proprietary/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:system/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    vendor/zte/p839v55/proprietary/etc/acdbdata/MTP/MTP_Headset_cal.acdb:system/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    vendor/zte/p839v55/proprietary/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:system/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/zte/p839v55/proprietary/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Bluetooth_cal.acdb:system/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Bluetooth_cal.acdb \
    vendor/zte/p839v55/proprietary/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_General_cal.acdb:system/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_General_cal.acdb \
    vendor/zte/p839v55/proprietary/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Global_cal.acdb:system/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Global_cal.acdb \
    vendor/zte/p839v55/proprietary/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Handset_cal.acdb:system/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Handset_cal.acdb \
    vendor/zte/p839v55/proprietary/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Hdmi_cal.acdb:system/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Hdmi_cal.acdb \
    vendor/zte/p839v55/proprietary/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Headset_cal.acdb:system/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Headset_cal.acdb \
    vendor/zte/p839v55/proprietary/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Speaker_cal.acdb:system/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Speaker_cal.acdb \
    vendor/zte/p839v55/proprietary/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb:system/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb \
    vendor/zte/p839v55/proprietary/etc/acdbdata/QRD/QRD_General_cal.acdb:system/etc/acdbdata/QRD/QRD_General_cal.acdb \
    vendor/zte/p839v55/proprietary/etc/acdbdata/QRD/QRD_Global_cal.acdb:system/etc/acdbdata/QRD/QRD_Global_cal.acdb \
    vendor/zte/p839v55/proprietary/etc/acdbdata/QRD/QRD_Handset_cal.acdb:system/etc/acdbdata/QRD/QRD_Handset_cal.acdb \
    vendor/zte/p839v55/proprietary/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb:system/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb \
    vendor/zte/p839v55/proprietary/etc/acdbdata/QRD/QRD_Headset_cal.acdb:system/etc/acdbdata/QRD/QRD_Headset_cal.acdb \
    vendor/zte/p839v55/proprietary/etc/acdbdata/QRD/QRD_Speaker_cal.acdb:system/etc/acdbdata/QRD/QRD_Speaker_cal.acdb \
    vendor/zte/p839v55/proprietary/vendor/lib/libacdb-fts.so:system/vendor/lib/libacdb-fts.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libFlacSwDec.so:system/vendor/lib/libFlacSwDec.so \
    vendor/zte/p839v55/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    vendor/zte/p839v55/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
    vendor/zte/p839v55/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so \
    vendor/zte/p839v55/proprietary/vendor/lib/soundfx/libhwdap.so:system/vendor/lib/soundfx/libhwdap.so \
    vendor/zte/p839v55/proprietary/vendor/lib/soundfx/libswdap.so:system/vendor/lib/soundfx/libswdap.so \
    vendor/zte/p839v55/proprietary/vendor/lib/hw/sound_trigger.primary.msm8916.so:system/vendor/lib/hw/sound_trigger.primary.msm8916.so

# Bluetooth
PRODUCT_COPY_FILES += \
    vendor/zte/p839v55/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/zte/p839v55/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/zte/p839v55/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so

# Camera
PRODUCT_COPY_FILES += \
    vendor/zte/p839v55/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/zte/p839v55/proprietary/lib/hw/camera.msm8916.so:system/lib/hw/camera.msm8916.so \
    vendor/zte/p839v55/proprietary/lib/libmm-qcamera.so:system/lib/libmm-qcamera.so \
    vendor/zte/p839v55/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    vendor/zte/p839v55/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    vendor/zte/p839v55/proprietary/lib/libqomx_core.so:system/lib/libqomx_core.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libactuator_bu64291gwz.so:system/vendor/lib/libactuator_bu64291gwz.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libactuator_bu64291gwz_camcorder.so:system/vendor/lib/libactuator_bu64291gwz_camcorder.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libactuator_bu64291gwz_camera.so:system/vendor/lib/libactuator_bu64291gwz_camera.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libchromatix_imx214_common.so:system/vendor/lib/libchromatix_imx214_common.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libchromatix_imx214_default_video.so:system/vendor/lib/libchromatix_imx214_default_video.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libchromatix_imx214_hfr_60.so:system/vendor/lib/libchromatix_imx214_hfr_60.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libchromatix_imx214_hfr_60fps.so:system/vendor/lib/libchromatix_imx214_hfr_60fps.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libchromatix_imx214_hfr_90fps.so:system/vendor/lib/libchromatix_imx214_hfr_90fps.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libchromatix_imx214_hfr_120.so:system/vendor/lib/libchromatix_imx214_hfr_120.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libchromatix_imx214_hfr_120fps.so:system/vendor/lib/libchromatix_imx214_hfr_120fps.so \
vendor/zte/p839v55/proprietary/vendor/lib/libchromatix_imx214_preview.so:system/vendor/lib/libchromatix_imx214_preview.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libchromatix_imx214_snapshot.so:system/vendor/lib/libchromatix_imx214_snapshot.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libchromatix_imx214_snapshot_hdr.so:system/vendor/lib/libchromatix_imx214_snapshot_hdr.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libchromatix_imx214_video_hd.so:system/vendor/lib/libchromatix_imx214_video_hd.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libchromatix_imx214_video_hdr.so:system/vendor/lib/libchromatix_imx214_video_hdr.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libchromatix_s5k5e2_common.so:system/vendor/lib/libchromatix_s5k5e2_common.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libchromatix_s5k5e2_default_video.so:system/vendor/lib/libchromatix_s5k5e2_default_video.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libchromatix_s5k5e2_eyeverify.so:system/vendor/lib/libchromatix_s5k5e2_eyeverify.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libchromatix_s5k5e2_liveshot.so:system/vendor/lib/libchromatix_s5k5e2_liveshot.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libchromatix_s5k5e2_preview.so:system/vendor/lib/libchromatix_s5k5e2_preview.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libchromatix_s5k5e2_snapshot.so:system/vendor/lib/libchromatix_s5k5e2_snapshot.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmmcamera_imx214.so:system/vendor/lib/libmmcamera_imx214.so \
	vendor/zte/p839v55/proprietary/vendor/lib/libmmcamera_s5k5e2.so:system/vendor/lib/libmmcamera_s5k5e2.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmmcamera_mt9m114.so:system/vendor/lib/libmmcamera_mt9m114.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmmcamera_ov5645.so:system/vendor/lib/libmmcamera_ov5645.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
	vendor/zte/p839v55/proprietary/vendor/lib/libmmcamera_hi256.so:system/vendor/lib/libmmcamera_hi256.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    vendor/zte/p839v55/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so

# Camera firmware
PRODUCT_COPY_FILES += \
    vendor/zte/p839v55/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    vendor/zte/p839v55/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    vendor/zte/p839v55/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/zte/p839v55/proprietary/etc/firmware/cpp_firmware_v1_4_0.fw:system/etc/firmware/cpp_firmware_v1_4_0.fw

# Color convertor
PRODUCT_COPY_FILES += \
    vendor/zte/p839v55/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so

# DRM
PRODUCT_COPY_FILES += \
    vendor/zte/p839v55/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/zte/p839v55/proprietary/vendor/lib/libdrmdecrypt.so:system/vendor/lib/libdrmdecrypt.so \
    vendor/zte/p839v55/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/zte/p839v55/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    vendor/zte/p839v55/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so

# GPS
PRODUCT_COPY_FILES += \
    vendor/zte/p839v55/proprietary/bin/location-mq:system/bin/location-mq \
    vendor/zte/p839v55/proprietary/bin/loc_launcher:system/bin/loc_launcher \
    vendor/zte/p839v55/proprietary/etc/permissions/com.qualcomm.location.xml:system/etc/permissions/com.qualcomm.location.xml \
    vendor/zte/p839v55/proprietary/etc/permissions/com.qualcomm.location.vzw_library.xml:system/etc/permissions/com.qualcomm.location.vzw_library.xml \
    vendor/zte/p839v55/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/zte/p839v55/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/zte/p839v55/proprietary/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
    vendor/zte/p839v55/proprietary/vendor/lib/liblowi_client.so:system/vendor/lib/liblowi_client.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libquipc_os_api.so:system/vendor/lib/libquipc_os_api.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libulp2.so:system/vendor/lib/libulp2.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libxtadapter.so:system/vendor/lib/libxtadapter.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libxtwifi_ulp_adaptor.so:system/vendor/lib/libxtwifi_ulp_adaptor.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libxtwifi_zpp_adaptor.so:system/vendor/lib/libxtwifi_zpp_adaptor.so

# Graphics
PRODUCT_COPY_FILES += \
    vendor/zte/p839v55/proprietary/etc/firmware/a420_pfp.fw:system/etc/firmware/a420_pfp.fw \
    vendor/zte/p839v55/proprietary/etc/firmware/a420_pm4.fw:system/etc/firmware/a420_pm4.fw \
    vendor/zte/p839v55/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/zte/p839v55/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/zte/p839v55/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/zte/p839v55/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/zte/p839v55/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/zte/p839v55/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/zte/p839v55/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libsc-a2xx.so:system/vendor/lib/libsc-a2xx.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so

# IRQ balance
PRODUCT_COPY_FILES += \
    vendor/zte/p839v55/proprietary/bin/msm_irqbalance:system/bin/msm_irqbalance

# Media
PRODUCT_COPY_FILES += \
    vendor/zte/p839v55/proprietary/lib/libOmxVdecHevc.so:system/lib/libOmxVdecHevc.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libDivxDrm.so:system/vendor/lib/libDivxDrm.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libExtendedExtractor.so:system/vendor/lib/libExtendedExtractor.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libHevcSwDecoder.so:system/vendor/lib/libHevcSwDecoder.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmmparser.so:system/vendor/lib/libmmparser.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libSHIMDivxDrm.so:system/vendor/lib/libSHIMDivxDrm.so

# NFC
PRODUCT_COPY_FILES += \
    vendor/zte/p839v55/proprietary/vendor/firmware/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so

PRODUCT_COPY_FILES += \
    vendor/zte/p839v55/proprietary/lib/hw/nfc_nci.pn54x.default.so:system/lib/hw/nfc_nci.pn54x.default.so

# Perf
PRODUCT_COPY_FILES += \
    vendor/zte/p839v55/proprietary/bin/perfd:system/bin/perfd \
    vendor/zte/p839v55/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so

# Postprocessing
PRODUCT_COPY_FILES += \
    vendor/zte/p839v55/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
    vendor/zte/p839v55/proprietary/vendor/lib/libdisp-aba.so:system/vendor/lib/libdisp-aba.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmm-abl.so:system/vendor/lib/libmm-abl.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmm-abl-oem.so:system/vendor/lib/libmm-abl-oem.so

# Qualcomm
PRODUCT_COPY_FILES += \
    vendor/zte/p839v55/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/zte/p839v55/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so

# Radio
PRODUCT_COPY_FILES += \
    vendor/zte/p839v55/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/zte/p839v55/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/zte/p839v55/proprietary/bin/radish:system/bin/radish \
    vendor/zte/p839v55/proprietary/bin/rfs_access:system/bin/rfs_access \
    vendor/zte/p839v55/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/zte/p839v55/proprietary/lib/librmnetctl.so:system/lib/librmnetctl.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so

# Sensors
PRODUCT_COPY_FILES += \
    vendor/zte/p839v55/proprietary/bin//sensord:system/bin/sensord \
    vendor/zte/p839v55/proprietary/lib/hw/sensors.msm8916.so:system/lib/hw/sensors.msm8916.so

# Thermal
PRODUCT_COPY_FILES += \
    vendor/zte/p839v55/proprietary/bin/thermal-engine:system/bin/thermal-engine \
    vendor/zte/p839v55/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libthermalioctl.so:system/vendor/lib/libthermalioctl.so

# Time services
PRODUCT_COPY_FILES += \
    vendor/zte/p839v55/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/zte/p839v55/proprietary/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
    vendor/zte/p839v55/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so

# Touchscreen
#PRODUCT_COPY_FILES += \
#    vendor/zte/p839v55/proprietary/bin/init.atmel_ts.sh:system/bin/init.atmel_ts.sh \
#    vendor/zte/p839v55/proprietary/etc/firmware/A4_15_2.2_AA.raw:system/etc/firmware/A4_15_2.2_AA.raw

# Venus (media) firmware
PRODUCT_COPY_FILES += \
    vendor/zte/p839v55/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    vendor/zte/p839v55/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    vendor/zte/p839v55/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    vendor/zte/p839v55/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    vendor/zte/p839v55/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    vendor/zte/p839v55/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    vendor/zte/p839v55/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt

# Widevine firmware
PRODUCT_COPY_FILES += \
    vendor/zte/p839v55/proprietary/etc/firmware/widevine.b00:system/etc/firmware/widevine.b00 \
    vendor/zte/p839v55/proprietary/etc/firmware/widevine.b01:system/etc/firmware/widevine.b01 \
    vendor/zte/p839v55/proprietary/etc/firmware/widevine.b02:system/etc/firmware/widevine.b02 \
    vendor/zte/p839v55/proprietary/etc/firmware/widevine.b03:system/etc/firmware/widevine.b03 \
    vendor/zte/p839v55/proprietary/etc/firmware/widevine.mdt:system/etc/firmware/widevine.mdt

# Wifi
PRODUCT_COPY_FILES += \
    vendor/zte/p839v55/proprietary/bin/ptt_socket_app:system/bin/ptt_socket_app \
    vendor/zte/p839v55/proprietary/bin/wcnss_service:system/bin/wcnss_service   \
    vendor/zte/p839v55/proprietary/lib/modules/pronto/pronto_wlan.ko:system/lib/modules/pronto/pronto_wlan.ko
    
# Misc
PRODUCT_COPY_FILES += \
    vendor/zte/p839v55/proprietary/bin/adjust_serialno:system/bin/adjust_serialno \
    vendor/zte/p839v55/proprietary/bin/adjust_settings:system/bin/adjust_settings

# Lights
PRODUCT_COPY_FILES += \
    vendor/zte/p839v55/proprietary/lib/hw/lights.msm8916.so:system/lib/hw/lights.msm8916.so
